title: Kalle Moen
author: Kalle Moen
subtitle: Product, design, and business. 

baseurl: ""

footer_only_homepage: true
repository: "kallemoen/kallemoen.com.git"

profile-picture: assets/headshot@2x.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Articles"
   link: "articles"
